version: '3.8'

services:    
  db:
    container_name: waxbox_mysql
    image: mysql:5.7
    ports:
      - "8089:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - waxbox_net

  wordpress:
    container_name: waxbox_wordpress
    depends_on:
      - db
    image: wordpress:5.5.1
    ports:
      - "8088:80"
    restart: always
    volumes:
      - ./wordpress/wp-app:/var/www/html:delegated
      - ./wordpress/wp-content/themes/:/var/www/html/wp-content/themes:delegated
      - ./wordpress/wp-content/plugins/:/var/www/html/wp-content/plugins:delegated
      - ./wordpress/wp-content/uploads/:/var/www/html/wp-content/uploads:cached
    environment:
      VIRTUAL_HOST: seltzer.local,*.seltzer.local
      VIRTUAL_PORT: 8088
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* JWT Auth */
        define('GRAPHQL_JWT_AUTH_SECRET_KEY', 'bd4d86b1eb246a3ddc3f30e870aa9956db104de2');
    networks:
      - waxbox_net

  wpcli:
    container_name: waxbox_wordpress_cli
    image: wordpress:cli
    volumes:
      - ./wordpress/wp-app:/var/www/html
    depends_on:
      - db
      - wordpress
    networks:
      - waxbox_net
  
  ui:
    container_name: waxbox_ui
    stdin_open: true
    depends_on:
      - db
      - wordpress
    build:
      context: ui
      dockerfile: ./Dockerfile
    volumes:
      - './ui/:/app'
      - './ui/app/node_modules'
    ports:
      - 3033:3000
    networks:
      - waxbox_net

networks:
  waxbox_net:
      driver: bridge

volumes:
    db_data: