version: '3.3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 3306:3306
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./etc/nginx/proxy.conf:/etc/nginx/proxy.conf
    networks:
      - default
    
  db:
    image: mysql:5.7
    ports:
      - "8089:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* JWT Auth */
        define('GRAPHQL_JWT_AUTH_SECRET_KEY', 'bd4d86b1eb246a3ddc3f30e870aa9956db104de2');
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:5.5.1
    ports:
      - "8088:80"
    restart: always
    volumes:
      - ./wp-app:/var/www/html:delegated
      - ./wp-content/themes/:/var/www/html/wp-content/themes:delegated
      - ./wp-content/plugins/:/var/www/html/wp-content/plugins:delegated
      - ./wp-content/uploads/:/var/www/html/wp-content/uploads:cached
    environment:
      VIRTUAL_HOST: seltzer.local,*.seltzer.local
      VIRTUAL_PORT: 8088
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - frontend
      - backend

  wpcli:
    image: wordpress:cli
    volumes:
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wordpress
    networks:
      - frontend
      - backend

networks:
  default:
    external:
      name: proxy
  backend:
  frontend:
    external:
      name: proxy

volumes:
    db_data: